apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: n4c4ptibh-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-3e009ef922.92a9.p3.openshiftapps.com/rhtap/rhtap-qe:2b892f9efac08cc291595bc66427e85fa94a9acb@sha256:0ddd3616a1ee9b61caf29a19982121955ca7ee5498dd61b27e684934335ecc2a
          name: container-image
